### ISSUE TITLE
ユーザーアカウントロック機能の実装

### ISSUE THREAD

**Issue by kumaryoya** [kumaryoya/test-app#14]
## 概要
ユーザーのアカウントロック機能を追加します。ログインに10回連続で失敗した場合、アカウントをロックし、ログインできないようにします。1時間後に自動的にロックを解除します。

### 1. ユーザーモデルにロック関連のカラムを追加

`users`テーブルにロック関連のカラムを追加するマイグレーションファイルを作成します：

```ruby
# db/migrate/YYYYMMDDHHMMSS_add_lockable_to_users.rb
class AddLockableToUsers < ActiveRecord::Migration[7.x]
  def change
    add_column :users, :failed_attempts, :integer, default: 0, null: false
    add_column :users, :locked_at, :datetime
    add_column :users, :unlock_token, :string
    
    add_index :users, :unlock_token, unique: true
  end
end
```

### 2. Userモデルに`:lockable`モジュールを追加

`User`モデルを修正して、Deviseの`:lockable`モジュールを有効にします：

```ruby
# app/models/user.rb
class User < ApplicationRecord
  # 既存のDeviseモジュールに加えて、:lockableを追加
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :validatable, 
         :lockable
  
  # 既存のコード...
end
```

### 3. Devise設定ファイルの更新

Deviseの設定ファイルを更新して、ロック機能のパラメータを設定します：

```ruby
# config/initializers/devise.rb

# 最大試行回数を10回に設定
config.lock_strategy = :failed_attempts
config.maximum_attempts = 10

# ロックの解除方法（1時間後に自動解除）
config.unlock_strategy = :time
config.unlock_in = 1.hour
```

### 4. ロックされたユーザー向けのメッセージをカスタマイズ

ユーザーに適切なフィードバックを提供するために、ロック関連のメッセージをカスタマイズします：

```yaml
# config/locales/devise.en.yml
en:
  devise:
    failure:
      locked: "アカウントがロックされています。1時間後に自動的に解除されます。"
    models:
      user:
        attributes:
          user:
            locked: "アカウントがロックされています"
```

### 5. ロック状態を管理するためのコントローラーの拡張（オプション）

必要に応じて、セッションコントローラーを拡張して、ロック状態を管理する追加機能を実装できます。

### 6. ロック状態を表示するビューの追加（オプション）

ユーザーがロックされた場合に表示するビューを追加できます。

### 7. 管理者向けのユーザーロック解除機能

管理者がユーザーのロックを手動で解除できる機能を追加することも検討できます。

## テスト項目

実装後は、以下のテストを実施してください：

1. 10回連続でログイン失敗するとアカウントがロックされることを確認
2. ロック状態では正しいパスワードを入力してもログインできないことを確認
3. 1時間後にロックが解除されることを確認（テスト時は時間を短く設定できます）
4. （管理機能を実装した場合）管理者がロックを手動で解除できることを確認

## 注意点

- 本番環境にデプロイする前に、十分なテストを行う
- ユーザーに対して、ロック機能について事前に通知することを検討する
- ロック解除のための代替手段（メール通知など）も検討する
